name: Build
on: 
  workflow_run:
    workflows: ["Integration tests"]
    types: [completed]
jobs:
  Integration-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build
      run: make build
    # - name: Draft release
    #   uses: release-drafter/release-drafter@v5
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
