name: Release to PYPI
on: 
  create:
    tags:
      - v*
jobs:
  release-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: make format
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        # body: |
        #   ${{ steps.Changelog.outputs.changelog }}
        draft: true
        prerelease: true
    - name: Set tag as package version
      run: echo "RISKMODELS_VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/v//')" >> $GITHUB_ENV
    - run: make build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
