name: Release to PYPI
on:  
  push:
    tags:
      - 'v*'
jobs:
  release-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Format modules with Black
      run: make format
    # - name: create release notes
    #   id: build_changelog
    #   uses: mikepenz/release-changelog-builder-action@{latest-release}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        # body: |
        #   ${{steps.build_changelog.outputs.changelog}}
        draft: false
        prerelease: false
    - name: Set tag as package version through an environment variable
      run: echo "RISKMODELS_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
    - name: Build package
      run: make build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
